package com.mycompany.HotelReservation;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Date;


public class InvoiceGenerator2 {
    private static int Userid;
    private static String Username;
    private static int UserPhone;
    private static String UserEmail;


    // Room Details var
    private static int RoomNumber;
    private static String RoomType;
    private static String BedType;
    private static int CalculatedPrice;

    // Check in and out details
    private static String UserCheckinDetails;
    private static String UserCheckOutDetails;



    // Fonts
    private static final Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static final Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static final Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static final Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);


    // Constructor.
//    InvoiceGenerator2(int id, String Name, int Phone, String Email, int Room, String Type, String Bed, int Price, String CheckinDetails, String CheckOutDetails) {
//        Userid = id;
//        Username = Name;
//        UserEmail = Email;
//        UserPhone = Phone;
//        RoomNumber = Room;
//        RoomType = Type;
//        BedType = Bed;
//        CalculatedPrice = Price;
//        UserCheckinDetails = CheckinDetails;
//        UserCheckOutDetails = CheckOutDetails;
//    }
    private static final String FILE = "out/invoices/" + 1 + ".pdf";

    public static void main(String[] args) {
        try
        {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            addMetaData(document);
            addTitle(document);
            document.close();
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }

    public static void addMetaData(Document document) {
        document.addAuthor("Gulshan Yadav");
        document.addCreator("Hotelopedia");
        document.addTitle("Invoice");
    }

    public static void addTitle(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        preface.add(new Paragraph("Hotelopedia", catFont));
        addEmptyLine(preface, 1);
        // Add the username of computer in pdf
        preface.add(new Paragraph(
                "Invoice generated by: " + System.getProperty("user.name") + ", " + new Date(), smallBold));

    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i= 0; i<number;i++){
            paragraph.add(new Paragraph(" "));
        }
    }

}
